// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreatePlayerNote(arg1:string,arg2:string):Promise<void>;

export function DeletePlayerNote(arg1:string,arg2:string):Promise<void>;

export function GetAppVersions():Promise<Array<string>>;

export function GetPlayerGameHistory(arg1:string):Promise<Array<main.PlayerGame>>;

export function GetPlayerIdsOptions():Promise<Array<main.PlayerIdsOption>>;

export function GetPlayerNotes(arg1:string):Promise<string>;

export function GetReplays(arg1:Array<string>):Promise<Array<main.WarnoData>>;

export function GetSettings():Promise<main.Settings>;

export function GetWarnoSaveFolders():Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<void>;
