// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyse(arg1:Array<string>):Promise<string>;

export function GetWarnoSaveFolders():Promise<string>;
