// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePlayerNote(arg1, arg2) {
  return window['go']['main']['App']['CreatePlayerNote'](arg1, arg2);
}

export function CreateTeamNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTeamNote'](arg1, arg2, arg3);
}

export function DeletePlayerNote(arg1, arg2) {
  return window['go']['main']['App']['DeletePlayerNote'](arg1, arg2);
}

export function DeleteTeamNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteTeamNote'](arg1, arg2, arg3);
}

export function GetAppVersions() {
  return window['go']['main']['App']['GetAppVersions']();
}

export function GetDailyRecap(arg1) {
  return window['go']['main']['App']['GetDailyRecap'](arg1);
}

export function GetPlayerGameHistory(arg1) {
  return window['go']['main']['App']['GetPlayerGameHistory'](arg1);
}

export function GetPlayerIdsOptions() {
  return window['go']['main']['App']['GetPlayerIdsOptions']();
}

export function GetPlayerNotes(arg1) {
  return window['go']['main']['App']['GetPlayerNotes'](arg1);
}

export function GetPlayerReplays(arg1) {
  return window['go']['main']['App']['GetPlayerReplays'](arg1);
}

export function GetReplays(arg1) {
  return window['go']['main']['App']['GetReplays'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSteamPlayer(arg1) {
  return window['go']['main']['App']['GetSteamPlayer'](arg1);
}

export function GetTeamNotes(arg1, arg2) {
  return window['go']['main']['App']['GetTeamNotes'](arg1, arg2);
}

export function GetWarnoSaveFolders() {
  return window['go']['main']['App']['GetWarnoSaveFolders']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchPlayerInApi(arg1) {
  return window['go']['main']['App']['SearchPlayerInApi'](arg1);
}

export function SendPlayersToAPI(arg1) {
  return window['go']['main']['App']['SendPlayersToAPI'](arg1);
}
