// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyse(arg1) {
  return window['go']['main']['App']['Analyse'](arg1);
}

export function GetWarnoSaveFolders() {
  return window['go']['main']['App']['GetWarnoSaveFolders']();
}
