// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreatePlayerNote(arg1:string,arg2:string):Promise<void>;

export function CreateTeamNote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeletePlayerNote(arg1:string,arg2:string):Promise<void>;

export function DeleteTeamNote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetAppVersions():Promise<Array<string>>;

export function GetDailyRecap(arg1:string):Promise<main.DailyRecap>;

export function GetEugenPlayer(arg1:string):Promise<main.EugenPlayer>;

export function GetLeaderboard():Promise<Array<main.LeaderboardEntry>>;

export function GetPlayerGameHistory(arg1:string):Promise<Array<main.PlayerGame>>;

export function GetPlayerIdsOptions():Promise<Array<main.PlayerIdsOption>>;

export function GetPlayerNotes(arg1:string):Promise<string>;

export function GetPlayerReplays(arg1:string):Promise<Array<main.GetReplay>>;

export function GetReplays(arg1:Array<string>):Promise<Array<main.WarnoData>>;

export function GetSettings():Promise<main.Settings>;

export function GetSteamPlayer(arg1:string):Promise<main.SteamPlayer>;

export function GetTeamNotes(arg1:string,arg2:string):Promise<string>;

export function GetWarnoSaveFolders():Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SearchPlayerInApi(arg1:string):Promise<Array<main.GetUser>>;

export function SendPlayersToAPI(arg1:Array<main.PostUser>):Promise<Record<string, boolean>>;
