name: build

on:
  push:
    branches:
      - master

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: warno-replays-analyser
          build-platform: windows/amd64
          package: true
